[package]
name = "carapax"
description = "A Telegram Bot Framework"
version = "0.2.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/carapax"
repository = "https://github.com/tg-rs/tg-rs"

[dependencies]
async-trait = "0.1"
carapax-codegen = { path = "../carapax-codegen" }
log = "0.4"
shellwords = "1"
tgbot = { path = "../tgbot" }
tokio = "0.2"

[dev-dependencies]
dotenv = "0.15"
env_logger = "0.7"
serde_json = "1"
tokio = { version = "0.2", features = ["macros"]}
